//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokemonParty.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartyDetail
    {
        public int IdTrack { get; set; }
        public int PartyID { get; set; }
        public int PokemonID { get; set; }
    
        public virtual Party Party { get; set; }
        public virtual PokemonInfo PokemonInfo { get; set; }
    }
}
