//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokemonParty.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PokemonInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PokemonInfo()
        {
            this.PartyDetails = new HashSet<PartyDetail>();
        }
    
        public int PokemonID { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public decimal AttackDMG { get; set; }
        public decimal HP { get; set; }
        public int Lvl { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartyDetail> PartyDetails { get; set; }
    }
}
